#[path = "common/arg.rs"]
pub mod arg;
#[path = "common/config.rs"]
pub mod config;
#[path = "common/handle.rs"]
pub mod handle;
#[path = "common/task.rs"]
pub mod task;
#[path = "common/trait_arg.rs"]
pub mod trait_arg;
#[path = "common/trait_task.rs"]
pub mod trait_task;
