[[task]]
id = 1
name = "Async Task"
command = "python"
args = ["-u", "./script/task.py"]
dir = "."
group = "g1"
env = {}
stdin = false
stdout = "./logs/output.txt"
stderr = "./logs/error.txt"
created_at = 1654345600
task_type = { Async = { max_restart = 2, has_restart = 0, started_at = 0, stopped_at = 0 } }

[[task]]
id = 2
name = "Periodic Task"
command = "python"
args = ["-u", "./script/task.py", "10"]
dir = "."
group = "g2"
env = {}
stdin = false
stdout = "./logs/output.txt"
stderr = "./logs/error.txt"
created_at = 1654345600
task_type = { Periodic = { interval = 5, last_run = 0, sync = false } }
